title: Sayr Olivares
site_name: Sayr Olivares
tagline: Data, reporting, and automation
description: Data, reporting and automation.
url: "https://sayrolivares.github.io"
lang: en
timezone: America/Bogota
markdown: kramdown
twitter:
  username: sayrolivares
  card: summary_large_image
author:
  name: Sayr Olivares
  url: https://sayrolivares.github.io/author/sayr-olivares.html
  twitter: sayrolivares
  github: sayrolivares
  linkedin: https://www.linkedin.com/in/sayrolivares/
  twitter_url: https://twitter.com/sayrolivares
  medium: https://medium.com/@sayrolivares
  substack: https://sayrolivares.substack.com/
  devto: https://dev.to/sayrolivares
social:
  name: Sayr Olivares
  links:
    - https://x.com/sayrolivares
    - https://www.linkedin.com/in/sayrolivares/
    - https://medium.com/@sayrolivares
    - https://sayrolivares.substack.com/
plugins:
  - jekyll-seo-tag
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/picture.jpg
  - scope:
      path: "posts"
    values:
      schema_type: BlogPosting
